media:
  public

content:
  - name: weekly
    label: 周记
    type: collection
    path: src/content/post
    filename:
      template: "{year}/{month}/{month}-{day}.md"
      field: create
    view:
      primary: title
      sort: ["publishDate", "desc"]
      filters:
        - field: draft
          default: false
    fields:
      - name: title
        label: 标题
        type: string
        required: true
        max_length: 60
      - name: description
        label: 描述
        type: text
        required: true
      - name: publishDate
        label: 发布日期
        type: date
        required: true
        format: "yyyy-MM-dd"
        default: "$CURRENT_DATE"
      - name: updatedDate
        label: 更新日期
        type: date
        format: "yyyy-MM-dd"
      - name: draft
        label: 草稿
        type: boolean
        default: true
      - name: pinned
        label: 置顶
        type: boolean
        default: false
      - name: body
        label: 正文
        type: rich-text

  - name: notes
    label: 笔记
    type: collection
    path: src/content/note
    filename:
      template: "{year}-{month}-{day}.md"
      field: create
    fields:
      - name: title
        label: 标题
        type: string
        required: true
        max_length: 60
      - name: description
        label: 描述
        type: text
      - name: publishDate
        label: 发布日期
        type: date
        required: true
        time: true
        default: "$CURRENT_DATETIME"
      - name: body
        label: 正文
        type: rich-text
